<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '2c2d2fe92db4cd03403dbb108ac263b7' => $vendorDir . '/codeinwp/gutenberg-menu-icons/load.php',
);
